name: Build EXE
on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: pip install -r requirements.txt pyinstaller
      - name: Build exe
        run: pyinstaller --onefile --windowed --name "RajVideoToolkit" --collect-all customtkinter --collect-all google --collect-all imageio_ffmpeg main.py
      - name: Upload exe
        uses: actions/upload-artifact@v4
        with:
          name: RajVideoToolkit
          path: dist/RajVideoToolkit.exe
